name: Rust CI & Auto Merge
permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  # build:
    # runs-on: ubuntu-latest
    # steps:
      # - uses: actions/checkout@v4
      # - name: Build
        # run: cargo build --verbose
      # - name: Run tests
        # run: cargo test --verbose

  auto-merge:
    # needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Enable Pull Request Automerge
      run: gh pr merge --squash --auto --repo ArturZinurov/rustlings ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
